query Products {
  products {
    nodes {
      category
      createdAt
      description
      image
      name
      price
      numberOfSold
      productId
      stockQuantity
      updatedAt
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
    }
  }
}