query Orders {
  orders {
    nodes {
      createdAt
      customerId
      orderDate
      orderId
      status
      totalAmount
      updatedAt
    }
    pageInfo {
      endCursor
      hasNextPage
      hasPreviousPage
      startCursor
    }
    edges {
      cursor
    }
  }
}

query GetOrdersApi {
  orders {
    nodes {
      orderDate
      orderId
      orderItems {
        product {
          name
        }
      }
      status
      totalAmount
      updatedAt
      customer {
        name
      }
    }
  }
}